Update automergerelease.yml

diff --git a/.github/workflows/automergerelease.yml b/.github/workflows/automergerelease.yml
--- a/.github/workflows/automergerelease.yml
+++ b/.github/workflows/automergerelease.yml
@@ -21,6 +21,13 @@ jobs:
    - name: get the branch
      run: |
          echo "MASTER_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
+         
+   - name: test
+     run: |
+       if [ "$GITHUB_EVENT_NAME" != "push" ]; then
+       echo "This job was triggered by a non-push event ($GITHUB_EVENT_NAME), failing.."
+       exit 1
+       fi 
        
    - name: Merge release branch to default branch
      run: |
